# The URL the site will be built for
base_url = "https://bonsaidb.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[link_checker]
skip_anchor_prefixes = [
    "https://github.com/khonsulabs/bonsaidb/blob/5216db14f621233c0a5f7f8ba2ac62c7508b3bd5/examples/open-library/examples/open-library.rs",
    "https://github.com/khonsulabs/nebari/blob/a6894b7c04938c35d4c69b161ae6985cf9de3ea5/nebari/src/tree/mod.rs",
    "https://github.com/khonsulabs/dossier/blob/7b5d1d393cab65cef633ec36b0ab7a7a37f2aacf/src/api.rs",
    "https://en.wikipedia.org/wiki/Cache_replacement_policies",
    "https://github.com/facebook/rocksdb/blob/bed40e7266b55349ce9d2dce27aeb2055813a5fe/env/io_posix.cc",
    "https://github.com/cockroachdb/pebble/blob/3355a02e7cec7a4cbf775421a89dfbe833818266/vfs/syncing_file_linux.go",
    "https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/sys/fcntl.h",
]

skip_prefixes = [
    "https://minority-game.gooey.rs", # cheap vps I chose not to renew due to unreliability, need to redeploy
    "https://khonsu.dev",             # dossier server, need to get back to that someday... not surprised it's down.
]

[extra]
# Put all your custom variables here
