on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: "Install Zola"
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.17.1/zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz

      - name: "Check"
        run: |
          ./zola check

      - name: "Build"
        run: |
          ./zola build

      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/

  deploy:
    runs-on: ubuntu-latest
    environment: bonsaidb.io
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: public
          
      - name: Deploy
        uses: khonsulabs/sync-to-dossier@main
        with:
          url: ${{ secrets.DOSSIER_URL }}
          api-key-id: ${{ secrets.DOSSIER_API_KEY_ID }}
          api-key: ${{ secrets.DOSSIER_API_KEY }}
          project: dossier
          from: public/
          to: /