on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: "Install Zola"
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.15.2/zola-v0.15.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.15.2-x86_64-unknown-linux-gnu.tar.gz

      - name: "Check"
        run: |
          ./zola check

      - name: "Build"
        run: |
          ./zola build

      - name: Deploy
        environment: khonsu.dev
        uses: khonsulabs/sync-to-dossier@main
        with:
          url: ${{ secrets.DOSSIER_URL }}
          api-key-id: ${{ secrets.DOSSIER_API_KEY_ID }}
          api-key: ${{ secrets.DOSSIER_API_KEY }}
          project: dossier
          from: public/
          to: /